version: '1'
services:
  ultralytics:
    image: yolov8
    volumes:
        - ./dataset_20231211:/dataset
        - ./models:/models
        - ./app:/app
    command: tail -f /dev/null
    ipc: host
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]